### ISSUE TITLE
[Request] Excursion Funnels and Hard Light Bridges

### ISSUE THREAD

**Issue by SirBlockles** [iChun/IssueTracker-PortalGun#1]
I would love it if you could add excursion funnels and possibly hard light bridges from Portal 2 to the mod. This could add so much more gameplay functionality.

**Comment by iChun** [comment]
I'll have to reimplement the other stuff missing from the mod for now, and the long promised gels first.. This will take a while. I'm going to close this issue for now until the time is right again.
