### ISSUE TITLE
client freeze with forge 703+

### ISSUE THREAD

**Issue by Sauge** [iChun/IssueTracker-PortalGun#10]
having client with forge 703 (tested it also with 708 and 710) no other mods (besides ichun util ofc)
acquirin any portal gun(well tested it with default and potato) putting it on your hotbar and selecting it
freezes the client without any kind of error

FML log https://dl.dropboxusercontent.com/u/22785141/ForgeModLoader-client-0.log

**Comment by vinterdo** [comment]
Its working for me on forge 703... Try updating ichun util and portal gun for newest release.

**Comment by iChun** [comment]
Yeah, try 1.5.2 of PortalGun and reply here if it's fixed.

**Comment by Sauge** [comment]
yeah kinda forgot about this, sorry.
Somehow fixed itself after couple of days(even before 1.5.2) no idea what changed so i guess you can just close this
