### ISSUE TITLE
Keeps Crashing

### ISSUE THREAD

**Issue by yukiifireguard** [iChun/IssueTracker-PortalGun#18]
here is the crash log from the .minecraft folder. 
http://pastebin.com/QFm8tKdc

**Comment by yukiifireguard** [comment]
Is anyone going to be able ot help me with this.

**Comment by Teslakoyal** [comment]
I would first try updating your Forge to the newest one witch at the time I write this is .804 then try it again. I use the ,804 version and have no issues running iChuns mods.

**Comment by iChun** [comment]
Incompatible argument to function = using the mod for minecraft version X on minecraft version Y. At the time this issue was submitted the mod was not updated to 1.6 yet and you tried to use it on 1.6, so that would be the issue.

Closed.

**Comment by yukiifireguard** [comment]
@Teslakoyal  and @iChun I got it working, I was installing it wrong. I always thought the iChun Util went in the core mods folder and the portal gun in the mods. Figured out BOTH go into the mods folder. Lol. So, user error. :)
