### ISSUE TITLE
Longfall boots not showing on Chractor

### ISSUE THREAD

**Issue by Teslakoyal** [iChun/IssueTracker-PortalGun#19]
Portal guns 2.0 for 1.6.2 like other mods seems to not be showing the texture on the actual character even with default resource pack.

Sorry if this is a known issue and I just couldn't find it on the other mod forums, as its across the board with all mods that I have updated to 1.6.2 like Industrialcraft 2, but vanilla Minecraft armors work just fine even with resource packs.

**Comment by Nykoload** [comment]
I think that may be because they have no mcmeta with the mods for the textures, could be wrong, but that's a "notification" I get in the console

**Comment by Teslakoyal** [comment]
I assume the issue is the same as the one from IC2, the target path in the .class file for the armor isn't targeting the Assets folder, it is targeting the old mod directory instead, I cant fix either of them myself as they aren't my mods. and even adding the old directory to the resource pack doesn't work as Minecraft seems to only look for the asset folder in the resource packs.

**Comment by Teslakoyal** [comment]
sorry for the accidental close, hit the wrong button :(

**Comment by iChun** [comment]
I'm aware of the issue and it has already been fixed my side. However, because of major changes to iChunUtil as well as ModJam, the update fixing this has been delayed due to it not being a very sever bug. I'll leave this thread open until an update is available.

**Comment by Teslakoyal** [comment]
Kool thanks for posting a response, sorta figured you were busy with Modjam and such :) thanks for making such a fun mod to use :)

**Comment by stubby1236** [comment]
my boots just show a black box around my legs,
any help?
