### ISSUE TITLE
Sentry Turret

### ISSUE THREAD

**Issue by Teslakoyal** [iChun/IssueTracker-PortalGun#21]
If I try to place it in the world the client crashes me to server select screen. Only if connected to a server.

**Comment by Teslakoyal** [comment]
I tried redoing my configs and it had no effect, when connected to a server, even with the latest iChun Utilities I get kicked to the server select screen, but as I look at my server logs looks like it might be an issue with MCPC entity placement, will let you know once they update to a newer version, since the current one also has the issue.

**Comment by khthe8th** [comment]
Having the same issues with latest builds of mcpc+, portal gun, and ichunutils on 1.6.2. Any thoughts ichun?

**Comment by iChun** [comment]
Just saw this. Is this still happening? A crash log would be nice.
