### ISSUE TITLE
Maybe Problem?

### ISSUE THREAD

**Issue by ghost** [iChun/IssueTracker-PortalGun#26]
So, I'm not sure if this is a problem, and idea/suggestion, or question. I'm kinda stuck here on my Modded Map. I'm making a little Portal course, and I need to clear the portals right? Easy. Hit the "R" key. Well, I can't trust that all players will follow through with this (plus I'm clearing their inventory, so they'd lose the portal gun). So, as the Emancipation Grill remains unfinished (which I understand is under development, and I am looking forward to its release), is their a command that would clear the portals? For example, "/clear portalgun.portals"? Just curious. Thank you for your work as well. It is truly amazing, and I believe you are most likely the strongest, single-man modder the Minecraft world has ever seen. Great Luck to you and your mods. 
                                                                                      Best Regards,
                                                                                                Novabutter

**Comment by AEnterprise** [comment]
what you can do is make a series of portal spawners, when those are activated the close the previous portal of that color and opens a new one there. the portal closes again when the redstone signal is turned off
