### ISSUE TITLE
Possibly Implement BlockBreak Events

### ISSUE THREAD

**Issue by dariusc93** [iChun/IssueTracker-PortalGun#28]
Since there are people who use protection mods (eg MyTown, Forge Essentials) and or plugins (for those who use mcpc), could you possibly implement the block break event that been implemented into forge? This could help many of those who use Portal Guns not to ban them or restrict them abit more easily than relaying on hackish methods (patching the mod directly or bytecode injection) to get the mod to respect the protected  areas.

**Comment by iChun** [comment]
.... 3 years later. An event is fired now when an EntityBlock is created. FTB Utilities makes use of this.
