### ISSUE TITLE
Portal Gun crashes world/server and makes it unplayable

### ISSUE THREAD

**Issue by Kirklen1** [iChun/IssueTracker-PortalGun#3]
This occured on feed the beast mindcrack version 8.2.0 with portal gun 1.4.7v5.

The short version is i picked up a wooden chest on a server with the portal gun and accidentally placed it on top of a portal that did not connect to another which crashed the server, i repeated this in single player with the same results and a unloadable map, disabling the mod makes the map loadable again

Also the ability to move chests defeats grief protection as they can be moved out of a protected area by an unauthorized player

http://pastebin.com/7MyGkGy5
my solution is to make it so it cannot pick up chests, movement or other grief protected items isn't likely preventable without a collaboration between you and the grief prevention mod developers.

it only seems to do this with wooden chests. chests from the iron chest mod just pop up and there contents come out

**Comment by iChun** [comment]
Fixed in next version of PG
