### ISSUE TITLE
Block breaks when shooting blue portals

### ISSUE THREAD

**Issue by francodml** [iChun/IssueTracker-PortalGun#30]
When I shoot a blue portal and I have a block selected (with selected I mean that I can break it/place a block on top), that block kinda "unloads" or breaks down. Like a Chunk Error but minimized to a block. If I place for example a diamond block where that block was, the block that was before reloads and replaces the diamond block. I'm using the last version of the Portal Gun. I'm on Windows 8 playing Singleplayer (Creative mode)

**Comment by iChun** [comment]
Already fixed in latest 1.7.10 versions
