### ISSUE TITLE
No 1.7?

### ISSUE THREAD

**Issue by s5bug** [iChun/IssueTracker-PortalGun#34]
I consider this an issue for me, because I would like to have Portal Guns in my 1.7.10 worlds. If you don't feel like doing the work yourself, I'll be happy to update the mod for you.

**Comment by iChun** [comment]
I'm skipping 1.7 mostly due to rendering issues. Expect a return for 1.8

**Comment by s5bug** [comment]
Well, good luck doing your models for 1.8! It's very challenging (for me.)

On 12/23/14, iChun notifications@github.com wrote:

> I'm skipping 1.7 mostly due to rendering issues. Expect a return for 1.8
> On 23 Dec 2014 00:08, "firestar115" notifications@github.com wrote:
> 
> > I consider this an issue for me, because I would like to have Portal Guns
> > in my 1.7.10 worlds. If you don't feel like doing the work yourself, I'll
> > be happy to update the mod for you.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/iChun/IssueTracker-PortalGun/issues/34.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/iChun/IssueTracker-PortalGun/issues/34#issuecomment-67932789

## 

```
 ___      .__   __. .___________. __    __    ______   .__   __.
```

---

```
/   \     |  \ |  | |           ||  |  |  |  /  __  \  |  \ |  |
```

\   \     /   /
   /  ^  \    |   |  | `---|  |----`|  |**|  | |  |  |  | |   |  |
\   \   /   /
  /  /_\  \   |  . `  |     |  |     |   __   | |  |  |  | |  . `  |
  _    _/
 /  ___**  \  |  |\   |     |  |     |  |  |  | |  `--'  | |  |\   |     |  |
/**/     \**\ |**| \**|     |**|     |**|  |**|  ____**/  |**| \**|     |__|
