### ISSUE TITLE
Still no sound

### ISSUE THREAD

**Issue by Calvin-13** [iChun/IssueTracker-PortalGun#35]
Simple. No sound for my PortalGun mod. I suspect it’s a download problem.

**Comment by renard162** [comment]
Same problem here, apparently a download problem too.

http://pastebin.com/2Z0Rsf2f

My minecraft still clean with forge 10.13.4.1481, iChunUtil-4.2.2 and PortalGun-4.0.0-beta-5.

**Comment by iChun** [comment]
Will be fixed in beta-6
