### ISSUE TITLE
Localization Support

### ISSUE THREAD

**Issue by labpaw** [iChun/IssueTracker-PortalGun#38]
@iChun very very waiting for it. Hope to see it in 1.7.10 Also, tile.PortalMod.name and tile.PortalMultiBlock.name have no names(missing localization)

**Comment by iChun** [comment]
All the localization support stuff will only be done in the 1.8 rewrite.

**Comment by iChun** [comment]
Added temporary (hardcoded) localization. Will be in the beta-6 update for 1.7.10
