### ISSUE TITLE
lastest version of iChunUtil doesn't work with latest portal gun

### ISSUE THREAD

**Issue by dmodoomsirius** [iChun/IssueTracker-PortalGun#40]
using version 5.4.0 of iChunUtil and version 4.0.0-beta-5 of portal gun and it requires iChunUtil 4.2.2
any chance of changing it so it works with the latest iChunUtil?

**Comment by iChun** [comment]
Kinda a late reply but use iChunUtil 4.X.X for mod versions 4.X.X, 5.X.X for 5.X.X etc. This will be rectified for 6.X.X versions of mods etc.

My bad.
