### ISSUE TITLE
Minetweaker Support?

### ISSUE THREAD

**Issue by BlakeBr0** [iChun/IssueTracker-PortalGun#42]
From research I've done (sorta) it seems Portal Gun (4.0.0 beta 5) registers recipes too late to be automatically changed by Minetweaker v3.0.10b. I hope this can get fixed.

**Comment by iChun** [comment]
The problem with this is that different servers may have different recipes
set for PG, so I only add the recipe after the server connect. If someone
could actually make a version of Minetweaker that checks for recipes about
5 seconds after login (I don't do this for only portalgun either, which
brings up another issue), then that would be great.

The silly thing about Minecraft is that you can add recipes at any point in
the game and have them work without any issue

**Comment by BlakeBr0** [comment]
Alright, makes sense. It really would be nice if Minetweaker could basically do /mt reload like 10 seconds after login to prevent any sort of issues like this. :P

**Comment by iChun** [comment]
Well it wouldn't be hard to write a quick mod that does that for you

**Comment by BlakeBr0** [comment]
Ya that would be pretty nice :P

**Comment by renard162** [comment]
Any chance to you make this little mod (to execute a command short time after server start) ? I search for a mod to autorun commands on server's start and the only one that I found is More Commands that conflict with many other mods.
