### ISSUE TITLE
crash report about portal gun

### ISSUE THREAD

**Issue by runescapejon** [iChun/IssueTracker-PortalGun#43]
Hello i have this crash report and i have no idea why am i getting this if anyone have any idea on how to fix this please help me please and thanks you 
http://pastebin.com/UaLjDJZ2

**Comment by iChun** [comment]
Should be fixed in beta-6

**Comment by runescapejon** [comment]
may i have the link to beta 6?

**Comment by iChun** [comment]
It's on curseforge
