### ISSUE TITLE
Portal Spawner bottom half vanishes 4.0.0 beta-5

### ISSUE THREAD

**Issue by koalalord9999** [iChun/IssueTracker-PortalGun#44]
I've been messing with portals on my server, the portal gun itself it banned, but the spawners are not. I place them around my base to access faster. I log out, server restarts all my portal spawners are now cut in half, and when broken they do not drop a portal spawner.

Picture of the now-chopped in half portal spawner:
![Half Portal Spawner](http://i.imgur.com/VL5ehBI.jpg)

**Comment by koalalord9999** [comment]
I can try to supply you with as much information as I possibly can.

**Comment by iChun** [comment]
There should be an error on the server side when the server starts,
hopefully. Drop that here if you find it. I also hear this issue doesn't
happen if your electrical source is somewhere else though.

**Comment by koalalord9999** [comment]
Alright, I'll ask the admins if they can post an errors concerning portalgun one startup :)

EDIT: Seems as though its not showing any issues now. They do turn off, but they don't disappear now. I've been leaving them powered on restart, maybe that has something to do with it. Not sure, they were not really keen on giving my the startup logs

**Comment by iChun** [comment]
It'll only show up the next time a portal spawner glitches though, mind you

**Comment by AetherWolf** [comment]
Ok so my portals don't cut in half, but every time I log off my portals from gun and spawner alike are gone which is really bad because I use them for worldwide travel with my guns on pedestals as attractions and with the spawners shutting down it ruins it...

**Comment by iChun** [comment]
I can't reproduce this, could you give me detailed steps to reproduce them?

**Comment by iChun** [comment]
Is chunkloading allowed on the server?

**Comment by koalalord9999** [comment]
Techincally no, but it still works for doing so. (If that was pointed at me ;) )

**Comment by iChun** [comment]
Have you tried enabling them to see if it fixes the issue?

**Comment by koalalord9999** [comment]
It seems that on our new Infinity Evolved server, this problem has fixed itself, not sure if because chunk loading is enabled or not, but neither spawner, or gun portals disappear. But a new problem has arisen lol, we can't edit the portal spawners, they are permanently tile.name.spawnerFrameEntity (or something like that, however, I believe that's what they have been even when they worked (through waila) even when placed in creative mode. (This is still the same version lol - I doubt it, but does having the press G to pickup blocks, disabled, break the portal spawner? I wouldn't imagine it would, but never know.. lol)

**Comment by iChun** [comment]
It shouldn't. What do you mean by editing Portal Spawners though? Does the
GUI pop up?

**Comment by koalalord9999** [comment]
By editing, I mean chaning the frequency of the portal. No GUI appears. You can however, give them redstone signal and they will turn on with the first frequency, of Blue, but that's the only one that appears.

**Comment by iChun** [comment]
Any error in the console?

**Comment by koalalord9999** [comment]
I'll have to make a video for you when I get home, it's hard to explain what's happening lol
I'll bring up console on the side so you can see when I place the portal what happens if anything does, also very sorry about late reply haven't seen the message in my email

**Comment by iChun** [comment]
please do thanks

**Comment by koalalord9999** [comment]
Here's the video https://youtu.be/e8vRPTTwmVs
and here's the console output from when I did /craft to when server restarted:

01.12 18:05:00 [Multicraft] Server ran command Stop
01.12 18:05:00 [Multicraft] Stopping server!
01.12 18:05:00 [Multicraft] Server ran command Start
01.12 18:05:00 [Multicraft] Server already running
01.12 18:05:00 [Server] INFO Tag Removed From EntityEnderman['Enderman'/527573, l='DIM-112', x=-254.15, y=79.00, z=10012.24]
01.12 18:04:31 [Server] INFO Players: [Traveler]name, |[Elder]|name, |[Elder]|Koala
01.12 18:04:31 [Server] INFO Staff: [Head-Admin]name, [AFK][OWNER]name
01.12 18:04:31 [Server] INFO CONSOLE issued server command: /list 
01.12 18:04:27 [Server] INFO koalalord9999 issued server command: /craft

**Comment by iChun** [comment]
Does this also happen without any other mods installed? This is a strange
issue. Possibly a modified jar?

**Comment by koalalord9999** [comment]
Pretty sure it's just the default install, but it is infinity evolved expert mode, that might have something to do with it
