### ISSUE TITLE
portals leaving

### ISSUE THREAD

**Issue by AetherWolf** [iChun/IssueTracker-PortalGun#45]
So every time I log off, any portals I have spawned with gun or spawner alike disappear. Help?

**Comment by iChun** [comment]
A bit late here, but what version of PG are you using?

**Comment by AetherWolf** [comment]
I don't remember. It was the latest posted one for 1.7.10

**Comment by iChun** [comment]
Well I can't reproduce it on SSP. Are you using this on SMP?

**Comment by AetherWolf** [comment]
I'm not quite sure what that means. :/

**Comment by iChun** [comment]
are you playing on single player or multiplayer

**Comment by AetherWolf** [comment]
Just a single player world

**Comment by iChun** [comment]
are you sure it's the latest version? I can't reproduce this on beta-5

**Comment by AetherWolf** [comment]
I can't actually see exactly what version I had when this posted, because
my entire modpack corrupted and I had to recreate it and I just left portal
gun out because it was having issues. I still use grab gun so I have your
util. I could do again and tell you  if it has issues

**Comment by iChun** [comment]
Please do, thanks

**Comment by AetherWolf** [comment]
OK. It will be later tonight though. I have work in 20
