### ISSUE TITLE
[WEBSITE ISSUE] Portal Gun 4.0.0-beta 4 and 5 download links lead to 404 errors.

### ISSUE THREAD

**Issue by bigyihsuan** [iChun/IssueTracker-PortalGun#46]
[image of the 404 page](http://i.imgur.com/gvWzW8c.png)
[Beta 5](http://new.creeperrepo.net/ichun/filespg/PortalGun-4.0.0-beta-5.jar)
[Beta 4](http://new.creeperrepo.net/ichun/filespg/PortalGun-4.0.0-beta-4.jar)

**Comment by iChun** [comment]
Already fixed
