### ISSUE TITLE
Crash with StarMiner

### ISSUE THREAD

**Issue by Shahelion** [iChun/IssueTracker-PortalGun#49]
Happens every so often when a mob tries to enter a portal, but not all the time.

https://gist.github.com/Zsashas/d76baeaec0d6d40e6d517b51a0475f6c

EDIT: Ok, almost every time.

**Comment by Shahelion** [comment]
So...any way to resolve this other than temporarily removing one of the two mods? 

Even a config to remove all portals from the world, that disables itself after running once, would be enough.

**Comment by iChun** [comment]
No longer a problem since I don't force entities to jump anymore.
