### ISSUE TITLE
Capable of shooting a portal inside a place from the outside or vice versa.

### ISSUE THREAD

**Issue by LycanLuck** [iChun/IssueTracker-PortalGun#5]
This was first discovered in FTB Ultimate v1.0.1 and PortalGun 1.4.7v5

I use a Windows 7 Toshiba laptop and yes this was on multiplayer but i have not tested on singleplayer.

Funny story, my friend made a jail with the iron bars inside some mountain and then I got placed there. I then got an idea to try to shoot a portal at one of the walls through the iron bars. At first i didnt think that the portal was made until i saw one of the reticles showed a filled up space. I then made myself another portal to see where it lead and the portal guided me outside of the mountain where he made the jail.

I have also tested this on warded blocks and it is very well possible to get through any block so long as there is a hollowed area (when i mean by a hallowed area i mean like a house or concave) with another wall on the other side.

http://pastebin.com/VfFj4Yek

I appreciate your time and work on this mod as I hope this was enough info to fix this issue. I enjoy this mod very much.

**Comment by iChun** [comment]
Fixed for next PG version.
