### ISSUE TITLE
[Question] Offline Chunk Loading

### ISSUE THREAD

**Issue by FruitizYum** [iChun/IssueTracker-PortalGun#53]
I've been told it's possible to stop portals from loading bases while the player is offline, but i can't seem to figure out how to do that. 

Is there a way to do this?

**Comment by iChun** [comment]
No. You've been told something wrong, I'm afraid.

**Comment by iChun** [comment]
The only option you have is to disable chunkloading for the mod altogether or to leave it be as is

**Comment by FruitizYum** [comment]
oki thanks!
