### ISSUE TITLE
Portals - Request Item ID or Automate Closing

### ISSUE THREAD

**Issue by oryfoxer** [iChun/IssueTracker-PortalGun#54]
I would like to close Portals after a time limit.

Is there a way to have life of the portal limited to a specific amount of time?

I want to automatically have opened portals removed after a few minutes on my server. What is the item ID for the portal that is generated so I can have them close after a specific time using a plugin?

**Comment by iChun** [comment]
I'm actually not sure, the code for PortalGun is so old now that I don't even remember if 1.7.10 (which is over 2 years old now) still uses block IDs or the new String registry system with FML.

If it uses the string registry system, you're going to have to pull the ID from the registry FML generates per server. It might actually be simpler to listen to tile entity creation for the portal tile entity and monitor it from there.

I'll consider adding this as a config option when PortalGun finally updates so leave the issue open for the time being.
