### ISSUE TITLE
crash report from Portal Gun Beta 6

### ISSUE THREAD

**Issue by runescapejon** [iChun/IssueTracker-PortalGun#55]
my server keep crashing with this
http://pastebin.com/Zg8VaHNr
and the only way to fix this is for me to delete a chunk that the crash report provide me the location
can you fix this so i don't have to keep doing this 

thanks

**Comment by iChun** [comment]
Don't use High Energy Pellets

**Comment by runescapejon** [comment]
Why not just fix the issue instead of not using an item from the mod ?
if this mod not going to get updates please let me know

**Comment by iChun** [comment]
Because I stopped supporting this version of PortalGun like a year ago so I
can focus my time (when I do have time) on rewriting and updating the mod
to later versions of Minecraft.

**Comment by iChun** [comment]
Unfortunately time is not something I have a lot of nowadays so an update
hasn't happened.

**Comment by runescapejon** [comment]
It's understandable thanks you

**Comment by JonL98** [comment]
Speaking of updating, perhaps you should put the source code here on GitHub along with your other mods. It makes rewriting and testing much easier with more than just one person doing it all, especially with all the coding changes that Minecraft has undergone since this mod's last update.

**Comment by runescapejon** [comment]
i totally agree on this, while your busy with stuff other developers can on in out of there free time and fix some of the issues

**Comment by iChun** [comment]
There are several reasons why Portal Gun and some other mods of mine aren't open source. Depending on how things go, Portal Gun and PiP may remain closed source. 

The other mods of mine which aren't open sourced though, I will be posting them on Github when they're updated for 1.10. [In fact some of those mods have already been posted on here](https://github.com/iChun?tab=repositories).

**Comment by iChun** [comment]
Well, this, rather.

![image](https://cloud.githubusercontent.com/assets/2298444/21195875/7fddc622-c22d-11e6-8047-d9879d900d27.png)
