### ISSUE TITLE
Game Crashes when I open a Portal

### ISSUE THREAD

**Issue by Fundryi** [iChun/IssueTracker-PortalGun#58]
After I open the second Portal it just crashes.

[crash-2017-04-12_09.36.26-client.txt](https://github.com/iChun/IssueTracker-PortalGun/files/915756/crash-2017-04-12_09.36.26-client.txt)

**Comment by iChun** [comment]
Can you try removing Optifine and reporting back?

**Comment by solarsonata** [comment]
I've been having this issue and I can confirm that removing optifine fixes it - however, this is problematic seeing as I basically need optifine to counter the lag created by see through portals. Not sure if this is fixable on your part though.

**Comment by iChun** [comment]
Optifine issue.

**Comment by Setadokalo** [comment]
It seems that it was done with intent, I think an @Optional may be necessary...
