### ISSUE TITLE
[Suggestion] Players in-between portals

### ISSUE THREAD

**Issue by solarsonata** [iChun/IssueTracker-PortalGun#60]
I really like how in the new version you can get mobs to be half in one portal and half in the other. Basically allowing for smooth travelling between. However, players still seem to just instantly jump to the other portal whenever they touch the first one. Would it be possible to implement smooth travelling for players as well, or would it take too much effort for the rewards?

**Comment by iChun** [comment]
This was actually my intention for being able to walk into portals but
because of a factor I overlooked in 1.10, I can't let you walk into the
portal too much because Minecraft will start forcing you out of it and it
was causing some issues.

**Comment by solarsonata** [comment]
Ah, thanks for the heads up! And now I feel stupid I didn't notice this in your blog post while I was reading it. :P

**Comment by DarianLStephens** [comment]
I'm still really hoping this is an issue you'll tackle at some point in the future; besides the improved rendering, it was the main feature I was hoping for.

**Comment by iChun** [comment]
Fixed in MC 1.12's version

**Comment by DarianLStephens** [comment]
Wait, so we can go in between portals in that version? That settles it; this is now the most accurate mod to a series I've ever seen. Well done, iChun!
 That probably doesn't mean much from a random nobody, but still, well done!
