### ISSUE TITLE
Crash after placing Portals

### ISSUE THREAD

**Issue by ghost** [iChun/IssueTracker-PortalGun#63]
So, i have a server with my own modpack and i recently added the portal gun mod but when i place 2 portals my screen turns to a light blue and then minecraft crashes (client side only)

I'm using version 6.0.1 for minecraft 1.10.2

Crash report: https://pastebin.com/q73yjXzy

**Comment by iChun** [comment]
Remove Optifine

**Comment by ghost** [comment]
i removed optifine but now i can't even start the game :(

Crash report: https://pastebin.com/X4trbwvL

**Comment by iChun** [comment]
Tcon crash, pass this over to them.

**Comment by ghost** [comment]
Ok, closing the issue now

**Comment by ghost** [comment]
Thanks for your help :)
