### ISSUE TITLE
1.10.2 Portal gun Mod Only Giving Me the Portal Guns

### ISSUE THREAD

**Issue by Duxtorm** [iChun/IssueTracker-PortalGun#64]
I Installed IChunUtil and The Portal gun mod... but there's a problem, it's literally just being the portal "gun" mod... because that's all it's giving me, no long fall boots or companion cubes or even a portal items tab.... just the guns. How do I fix this?

**Comment by DarianLStephens** [comment]
Okay, this is a really easy fix, but it is time consuming:
What you do is wait until those items are re-added.
