### ISSUE TITLE
[1.7.10] No sound for anything associated with Portal Gun - 4.0.0 beta 6

### ISSUE THREAD

**Issue by TheAbominableSbm** [iChun/IssueTracker-PortalGun#65]
Hello,

I'm aware this was an issue reported a lot and one you spoke about in the FAQ of the mod on your site. I've looked through your github issues and can see that this was supposedly fixed in beta 6, the version I'm using however I'm still having the issue.

I've scoured the internet looking for a way to manually retrieve the files, I've spent hours trying to find out how to add them myself but with no luck.

I just don't get why it has problems with the sound, when I have a large list of other mods which have their own sounds and function just fine (Mo Creatures for example)- though I'm no mod creator so of course there's a million reasons why I wouldn't know!

This is of course getting increasingly frustrating, especially as when I tested 4.0.0 beta **5** on my friend's PC last week, the sounds were there...yet when I launched the game today they were gone.

I know 1.7.10 is an old version of minecraft, but it's the only version I can play with all of the mods I used to enjoy, as a lot of mods have not been able to update past that point.

Furthermore, I'd like to add this mod to my private modpack (as in, only used between my friends and me) and am aware that you only permit versions prior to 1.8.

Is there anything that can be done or any workarounds you could provide me with? This is driving me insane!

Many thanks in advance,
Sam

PS. I am out on work at this moment but can get you any log files you may need - I have noticed that the launcher log _always_ has "connection error timed out" or something along those lines when the game is launched and I search/CTRL+F "portal", and it displays this with "resource" on the same line. 

Again, I can fetch the launcher log once I'm home if you need it.

**Comment by TheAbominableSbm** [comment]
Forgot to add I also know you dropped support for 1.7.10, but is there nothing that can be done for those of us who are stuck on older versions due to older mods not moving past 1.7.10?

**Comment by imjuniper** [comment]
https://minecraft.curseforge.com/projects/portal-gun/files/2480016
The latest file should fix it
