### ISSUE TITLE
Portal Gun Mod Not Making Sounds

### ISSUE THREAD

**Issue by Minecraft420** [iChun/IssueTracker-PortalGun#66]
Mods installed:
Mr crayfish's furniture mod (cfm)
Dynamic Transport
Gravity gun (makes sounds)
iChunUtil4.2.3
malisiscore
malisisdoors
new stefinus 3d guns mod
optifine
portal blocks
portal gun mod (not making sound)
SlimeVoid library
worldedit mod
I have the config of _enable mod sounds_ set to 1
and its still not making sound...
P.S when are you going to update the mod to have the material emancipation grid
because I need it for my portal 2 map (im using 1.7.10)

**Comment by imjuniper** [comment]
https://minecraft.curseforge.com/projects/portal-gun/files/2480016
The latest file should fix it
