### ISSUE TITLE
is it possible to shoot a portal on a slope?

### ISSUE THREAD

**Issue by neumannfe** [iChun/IssueTracker-PortalGun#69]
So i want to make a portal map for myself and i need to know if it is possible to have a portal on a slope from architecturecraft or carpenterblocks.i have tried it wich a carpenters slope in 1.7.10 but it did not work.so i want to kknow if it is planned, a bug ,impossible or possible on another slope.

**Comment by iChun** [comment]
No slopes. Hard to do right  with the way MC works.

**Comment by neumannfe** [comment]
ok,thanks for that quick answer ,so i have to find another solution.
