### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by ghost** [iChun/IssueTracker-PortalGun#7]
I need a bit of clarification please. I am being told that an 'FTB Private Pack' isn't considered a Private pack, and there for your post at http://ichun.us/support/mod-packs/ about FTB Private Packs is void due to the fact the I am not a part of the FTB Team, though I read it to mean this is fine? Can someone, or best of all iChun himself, give a bit of clarification?

**Comment by iChun** [comment]
Updated the page to clear a bit of confusion: Here's the main gist: "For Private FTB Packs, you have permission to include it, as long as the FTB Team has permission to use the mod in their own packs."
