### ISSUE TITLE
ID Mismatches

### ISSUE THREAD

**Issue by ghost** [iChun/IssueTracker-PortalGun#8]
So I open minecraft generate a new world, Close minecraft and then launch and open the generated world again and it throws an ID Mismatch.

The pastebin link is here: http://pastebin.com/PXZt4au0

Even ID Resolver wont fix the issue (I tried)

Many thanks.

**Comment by iChun** [comment]
Can I have the full FML log?

**Comment by ghost** [comment]
Yes here it is: http://pastebin.com/RNCKw8Zm

Cheers.

**Comment by iChun** [comment]
Can you try removing ID Resolver? It may be conflicting.

**Comment by ghost** [comment]
Heres the paste without ID Resolver: http://pastebin.com/gHLb4ZTM

Still getting same issue.

Cheers.

**Comment by iChun** [comment]
Can I see your portalgun config now instead? both the world config and the global config.

**Comment by ghost** [comment]
Hi this is the config file: http://pastebin.com/7WSCb2wB

And the one from World folder: http://pastebin.com/xiCcdVJM

Cheers.

**Comment by iChun** [comment]
Can you set itemIdIndex to 13212 or 13204 if the first one fails and see what happens? I'm merely debugging from guesses now, tbh. I don't know what's causing it.

**Comment by ghost** [comment]
Sorry for late response.

Heres after setting to 13212: http://pastebin.com/K4WR1zVB
and after setting to 13204: http://pastebin.com/bKZqtm2R

Both resulting in the same problem.

Many thanks for your continued support :)

**Comment by iChun** [comment]
Is it not possible to ignore the error? Or get rid of that stupid ItemTracker nonsense (I never liked it). It seems to be causing more issues than not.

**Comment by labpaw** [comment]
@iChun go close it? This is too old.

**Comment by iChun** [comment]
This entire repo is meant to be scrapped off when PG1.8 is completed.
