### ISSUE TITLE
Portal gun does not work

### ISSUE THREAD

**Issue by sharkck** [iChun/IssueTracker-PortalGun#83]
Using Minecraft 1.12.2 and portalgun version 7.0.2.

Left/right clicking does not cast a portal.  Left-clicking causes a little rubble effect on any block but that's it.  Is the mod broken for 1.12.2?

**Comment by sharkck** [comment]
After crafting the portal gun, I spawned in all of the other types via /give and even the stock guns (atlas, etc.) do not work.

**Comment by sharkck** [comment]
Ok.  Loaded it up Singleplayer and got the portal crosshair and everything without any issues. Connect back to the server and the portal crosshair does not show and the gun does nothing.

**Comment by sharkck** [comment]
Also, to note, since there doesn't seem to be an 'official' gravity gun section, the gravity gun acts the same way on the server.  It does nothing but the little particle thing on a block when you get close to it and left-click.

**Comment by sharkck** [comment]
I happened to be looking through the other areas of your github and found this post.  Confirmed that the portal cursor does not appear while an item is in the offhand.  As soon as I removed my offhand, the portal gun cursor appears and I'm able to make portals.
https://github.com/iChun/IssueTracker-Mods/issues/136

**Comment by iChun** [comment]
It's as intended. Portal Guns and Gravity Guns are *two handed* items. Having an item in off hand will prevent you from using it. The item render is lowered and bent to the side to notify the player that you can't use the item.
